#!/usr/bin/env bash
# Script 100-fix_in_7_lines_or_less starts nginx as nginx user
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
sudo nginx -c "service nginx restart"
